#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the
# string Ceci n'est pas une page

# Install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/custom_404' <<EOL
server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;

    location / {
        try_files \$uri =404;
    }

    error_page 404 /custom_404.html;

    location = /custom_404.html {
        internal;
    }
}
EOL

# Create a symbolic link to enable the custom 404 configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart
