#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument. Requirements:
# Accepts a string as an argument
# Displays 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}' if no argument passed
# Pings the IP 5 times

if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
IP_ADDRESS="$1"

# Ping the IP address 5 times
for i in {1..5}; do
    ping -c 1 "$IP_ADDRESS" > /dev/null
    if [ $? -eq 0 ]; then
        echo "$IP_ADDRESS is reachable"
    else
        echo "$IP_ADDRESS is not reachable"
    fi
done
